//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PattiFlow
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgentAdvance
    {
        public int VoucherNumber { get; set; }
        public string Date { get; set; }
        public string AgentName { get; set; }
        public Nullable<int> AdvanceAmount { get; set; }
        public string Narration { get; set; }
    }
}
