//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PattiFlow
{
    using System;
    using System.Collections.Generic;
    
    public partial class FreightVoucher
    {
        public int InvoiceNo { get; set; }
        public Nullable<decimal> FreightAmount { get; set; }
        public Nullable<decimal> FreightAdvance { get; set; }
        public Nullable<decimal> FreightBalance { get; set; }
        public string Narration { get; set; }
    
        public virtual PurchaseOrder PurchaseOrder { get; set; }
    }
}
