//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PattiFlow
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lorry
    {
        public int ID { get; set; }
        public Nullable<int> LorryNumber { get; set; }
        public string DriverName { get; set; }
        public Nullable<int> DriverPhoneNumber { get; set; }
    }
}
