//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PattiFlow
{
    using System;
    using System.Collections.Generic;
    
    public partial class PattiCreation
    {
        public int Id { get; set; }
        public int PattiNumber { get; set; }
        public int VoucherNumber { get; set; }
        public string Date { get; set; }
        public string AgentName { get; set; }
        public string AgentPlace { get; set; }
        public Nullable<int> AdvanceAmount { get; set; }
        public string Weighment { get; set; }
        public string WeighBridgeLess { get; set; }
        public string Gunnies { get; set; }
        public string PurchaseType { get; set; }
        public Nullable<int> BagWeight { get; set; }
        public string GunnyWeight { get; set; }
        public Nullable<int> CommPerBag { get; set; }
        public Nullable<int> RusumPerBag { get; set; }
        public Nullable<int> Lesskg { get; set; }
    }
}
