//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PattiFlow
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PattiFlowEntities : DbContext
    {
        public PattiFlowEntities()
            : base("name=PattiFlowEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<Agent> Agents { get; set; }
        public virtual DbSet<Godown> Godowns { get; set; }
        public virtual DbSet<ItemDescription> ItemDescriptions { get; set; }
        public virtual DbSet<ItemType> ItemTypes { get; set; }
        public virtual DbSet<Lorry> Lorries { get; set; }
        public virtual DbSet<PurchaseOrder> PurchaseOrders { get; set; }
        public virtual DbSet<PurchaseType> PurchaseTypes { get; set; }
        public virtual DbSet<PurchaseOrderItem> PurchaseOrderItems { get; set; }
        public virtual DbSet<FreightVoucher> FreightVouchers { get; set; }
        public virtual DbSet<AgentAdvance> AgentAdvances { get; set; }
        public virtual DbSet<PattiCreation> PattiCreations { get; set; }
        public virtual DbSet<PattiItem> PattiItems { get; set; }
    }
}
