//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PattiFlow
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrderItem
    {
        public int ID { get; set; }
        public string ItemType { get; set; }
        public string ItemDescription { get; set; }
        public string GodownName { get; set; }
        public Nullable<int> NumberOfGunnies { get; set; }
        public Nullable<int> BagWeight { get; set; }
        public Nullable<int> NumberOfBags { get; set; }
        public Nullable<int> ExcessShortkgs { get; set; }
        public Nullable<int> NetWeight { get; set; }
        public Nullable<int> Rate { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<int> PurchaseOrderId { get; set; }
    
        public virtual PurchaseOrder PurchaseOrder { get; set; }
    }
}
